/**
 * CF Pages middleware — handles all 301 redirects
 * Fires before any page or function is served.
 */

const REDIRECTS = {
  // Root service slugs -> /services/ hubs
  '/carpet-cleaning/': '/services/carpet-cleaning/',
  '/air-duct-cleaning/': '/services/air-duct-cleaning/',
  '/water-damage-restoration/': '/services/water-damage-restoration/',
  '/mold-remediation/': '/services/mold-remediation/',
  '/fire-smoke-restoration/': '/services/fire-smoke-restoration/',
  '/soda-blasting/': '/services/soda-blasting/',
  '/vapor-barrier/': '/services/vapor-barrier/',

  // /service/ (singular) -> /services/
  '/service/carpet-cleaning/': '/services/carpet-cleaning/',
  '/service/air-duct-cleaning/': '/services/air-duct-cleaning/',
  '/service/water-damage-restoration/': '/services/water-damage-restoration/',
  '/service/mold-removal/': '/services/mold-remediation/',
  '/service/fire-and-smoke-restoration/': '/services/fire-smoke-restoration/',
  '/service/soda-blasting/': '/services/soda-blasting/',
  '/service/vapor-barrier-installation/': '/services/vapor-barrier/',

  // areas-served non-ks -> ks
  '/areas-served/andover/': '/areas-served/andover-ks/',
  '/areas-served/augusta/': '/areas-served/augusta-ks/',
  '/areas-served/bel-aire/': '/areas-served/bel-aire-ks/',
  '/areas-served/benton/': '/areas-served/benton-ks/',
  '/areas-served/burns/': '/areas-served/burns-ks/',
  '/areas-served/cassoday/': '/areas-served/cassoday-ks/',
  '/areas-served/clearwater/': '/areas-served/clearwater-ks/',
  '/areas-served/derby/': '/areas-served/derby-ks/',
  '/areas-served/douglass/': '/areas-served/douglass-ks/',
  '/areas-served/eastborough/': '/areas-served/eastborough-ks/',
  '/areas-served/el-dorado/': '/areas-served/el-dorado-ks/',
  '/areas-served/eureka/': '/areas-served/eureka-ks/',
  '/areas-served/goddard/': '/areas-served/goddard-ks/',
  '/areas-served/haysville/': '/areas-served/haysville-ks/',
  '/areas-served/leon/': '/areas-served/leon-ks/',
  '/areas-served/maize/': '/areas-served/maize-ks/',
  '/areas-served/newton/': '/areas-served/newton-ks/',
  '/areas-served/park-city/': '/areas-served/park-city-ks/',
  '/areas-served/potwin/': '/areas-served/potwin-ks/',
  '/areas-served/rosalia/': '/areas-served/rosalia-ks/',
  '/areas-served/rose-hill/': '/areas-served/rose-hill-ks/',
  '/areas-served/sedgwick/': '/areas-served/sedgwick-ks/',
  '/areas-served/valley-center/': '/areas-served/valley-center-ks/',
  '/areas-served/whitewater/': '/areas-served/whitewater-ks/',
  '/areas-served/wichita/': '/areas-served/wichita-ks/',

  // water-damage-restoration non-ks -> ks
  '/water-damage-restoration/andover/': '/water-damage-restoration/andover-ks/',
  '/water-damage-restoration/augusta/': '/water-damage-restoration/augusta-ks/',
  '/water-damage-restoration/bel-aire/': '/water-damage-restoration/bel-aire-ks/',
  '/water-damage-restoration/benton/': '/water-damage-restoration/benton-ks/',
  '/water-damage-restoration/burns/': '/water-damage-restoration/burns-ks/',
  '/water-damage-restoration/cassoday/': '/water-damage-restoration/cassoday-ks/',
  '/water-damage-restoration/clearwater/': '/water-damage-restoration/clearwater-ks/',
  '/water-damage-restoration/derby/': '/water-damage-restoration/derby-ks/',
  '/water-damage-restoration/douglass/': '/water-damage-restoration/douglass-ks/',
  '/water-damage-restoration/eastborough/': '/water-damage-restoration/eastborough-ks/',
  '/water-damage-restoration/el-dorado/': '/water-damage-restoration/el-dorado-ks/',
  '/water-damage-restoration/eureka/': '/water-damage-restoration/eureka-ks/',
  '/water-damage-restoration/goddard/': '/water-damage-restoration/goddard-ks/',
  '/water-damage-restoration/haysville/': '/water-damage-restoration/haysville-ks/',
  '/water-damage-restoration/leon/': '/water-damage-restoration/leon-ks/',
  '/water-damage-restoration/maize/': '/water-damage-restoration/maize-ks/',
  '/water-damage-restoration/newton/': '/water-damage-restoration/newton-ks/',
  '/water-damage-restoration/park-city/': '/water-damage-restoration/park-city-ks/',
  '/water-damage-restoration/potwin/': '/water-damage-restoration/potwin-ks/',
  '/water-damage-restoration/rosalia/': '/water-damage-restoration/rosalia-ks/',
  '/water-damage-restoration/rose-hill/': '/water-damage-restoration/rose-hill-ks/',
  '/water-damage-restoration/sedgwick/': '/water-damage-restoration/sedgwick-ks/',
  '/water-damage-restoration/valley-center/': '/water-damage-restoration/valley-center-ks/',
  '/water-damage-restoration/whitewater/': '/water-damage-restoration/whitewater-ks/',
  '/water-damage-restoration/wichita/': '/water-damage-restoration/wichita-ks/',

  // /services/ non-ks city variants -> ks (fire-smoke-restoration)
  '/services/fire-smoke-restoration/andover/': '/services/fire-smoke-restoration/andover-ks/',
  '/services/fire-smoke-restoration/augusta/': '/services/fire-smoke-restoration/augusta-ks/',
  '/services/fire-smoke-restoration/bel-aire/': '/services/fire-smoke-restoration/bel-aire-ks/',
  '/services/fire-smoke-restoration/benton/': '/services/fire-smoke-restoration/benton-ks/',
  '/services/fire-smoke-restoration/burns/': '/services/fire-smoke-restoration/burns-ks/',
  '/services/fire-smoke-restoration/cassoday/': '/services/fire-smoke-restoration/cassoday-ks/',
  '/services/fire-smoke-restoration/clearwater/': '/services/fire-smoke-restoration/clearwater-ks/',
  '/services/fire-smoke-restoration/derby/': '/services/fire-smoke-restoration/derby-ks/',
  '/services/fire-smoke-restoration/douglass/': '/services/fire-smoke-restoration/douglass-ks/',
  '/services/fire-smoke-restoration/eastborough/': '/services/fire-smoke-restoration/eastborough-ks/',
  '/services/fire-smoke-restoration/el-dorado/': '/services/fire-smoke-restoration/el-dorado-ks/',
  '/services/fire-smoke-restoration/eureka/': '/services/fire-smoke-restoration/eureka-ks/',
  '/services/fire-smoke-restoration/goddard/': '/services/fire-smoke-restoration/goddard-ks/',
  '/services/fire-smoke-restoration/haysville/': '/services/fire-smoke-restoration/haysville-ks/',
  '/services/fire-smoke-restoration/leon/': '/services/fire-smoke-restoration/leon-ks/',
  '/services/fire-smoke-restoration/maize/': '/services/fire-smoke-restoration/maize-ks/',
  '/services/fire-smoke-restoration/newton/': '/services/fire-smoke-restoration/newton-ks/',
  '/services/fire-smoke-restoration/park-city/': '/services/fire-smoke-restoration/park-city-ks/',
  '/services/fire-smoke-restoration/potwin/': '/services/fire-smoke-restoration/potwin-ks/',
  '/services/fire-smoke-restoration/rosalia/': '/services/fire-smoke-restoration/rosalia-ks/',
  '/services/fire-smoke-restoration/rose-hill/': '/services/fire-smoke-restoration/rose-hill-ks/',
  '/services/fire-smoke-restoration/sedgwick/': '/services/fire-smoke-restoration/sedgwick-ks/',
  '/services/fire-smoke-restoration/valley-center/': '/services/fire-smoke-restoration/valley-center-ks/',
  '/services/fire-smoke-restoration/whitewater/': '/services/fire-smoke-restoration/whitewater-ks/',
  '/services/fire-smoke-restoration/wichita/': '/services/fire-smoke-restoration/wichita-ks/',

  // /services/ non-ks -> ks (mold-remediation)
  '/services/mold-remediation/andover/': '/services/mold-remediation/andover-ks/',
  '/services/mold-remediation/augusta/': '/services/mold-remediation/augusta-ks/',
  '/services/mold-remediation/bel-aire/': '/services/mold-remediation/bel-aire-ks/',
  '/services/mold-remediation/benton/': '/services/mold-remediation/benton-ks/',
  '/services/mold-remediation/burns/': '/services/mold-remediation/burns-ks/',
  '/services/mold-remediation/cassoday/': '/services/mold-remediation/cassoday-ks/',
  '/services/mold-remediation/clearwater/': '/services/mold-remediation/clearwater-ks/',
  '/services/mold-remediation/derby/': '/services/mold-remediation/derby-ks/',
  '/services/mold-remediation/douglass/': '/services/mold-remediation/douglass-ks/',
  '/services/mold-remediation/eastborough/': '/services/mold-remediation/eastborough-ks/',
  '/services/mold-remediation/el-dorado/': '/services/mold-remediation/el-dorado-ks/',
  '/services/mold-remediation/eureka/': '/services/mold-remediation/eureka-ks/',
  '/services/mold-remediation/goddard/': '/services/mold-remediation/goddard-ks/',
  '/services/mold-remediation/haysville/': '/services/mold-remediation/haysville-ks/',
  '/services/mold-remediation/leon/': '/services/mold-remediation/leon-ks/',
  '/services/mold-remediation/maize/': '/services/mold-remediation/maize-ks/',
  '/services/mold-remediation/newton/': '/services/mold-remediation/newton-ks/',
  '/services/mold-remediation/park-city/': '/services/mold-remediation/park-city-ks/',
  '/services/mold-remediation/potwin/': '/services/mold-remediation/potwin-ks/',
  '/services/mold-remediation/rosalia/': '/services/mold-remediation/rosalia-ks/',
  '/services/mold-remediation/rose-hill/': '/services/mold-remediation/rose-hill-ks/',
  '/services/mold-remediation/sedgwick/': '/services/mold-remediation/sedgwick-ks/',
  '/services/mold-remediation/valley-center/': '/services/mold-remediation/valley-center-ks/',
  '/services/mold-remediation/whitewater/': '/services/mold-remediation/whitewater-ks/',
  '/services/mold-remediation/wichita/': '/services/mold-remediation/wichita-ks/',

  // /services/ non-ks -> ks (soda-blasting)
  '/services/soda-blasting/andover/': '/services/soda-blasting/andover-ks/',
  '/services/soda-blasting/augusta/': '/services/soda-blasting/augusta-ks/',
  '/services/soda-blasting/bel-aire/': '/services/soda-blasting/bel-aire-ks/',
  '/services/soda-blasting/benton/': '/services/soda-blasting/benton-ks/',
  '/services/soda-blasting/burns/': '/services/soda-blasting/burns-ks/',
  '/services/soda-blasting/cassoday/': '/services/soda-blasting/cassoday-ks/',
  '/services/soda-blasting/clearwater/': '/services/soda-blasting/clearwater-ks/',
  '/services/soda-blasting/derby/': '/services/soda-blasting/derby-ks/',
  '/services/soda-blasting/douglass/': '/services/soda-blasting/douglass-ks/',
  '/services/soda-blasting/eastborough/': '/services/soda-blasting/eastborough-ks/',
  '/services/soda-blasting/el-dorado/': '/services/soda-blasting/el-dorado-ks/',
  '/services/soda-blasting/eureka/': '/services/soda-blasting/eureka-ks/',
  '/services/soda-blasting/goddard/': '/services/soda-blasting/goddard-ks/',
  '/services/soda-blasting/haysville/': '/services/soda-blasting/haysville-ks/',
  '/services/soda-blasting/leon/': '/services/soda-blasting/leon-ks/',
  '/services/soda-blasting/maize/': '/services/soda-blasting/maize-ks/',
  '/services/soda-blasting/newton/': '/services/soda-blasting/newton-ks/',
  '/services/soda-blasting/park-city/': '/services/soda-blasting/park-city-ks/',
  '/services/soda-blasting/potwin/': '/services/soda-blasting/potwin-ks/',
  '/services/soda-blasting/rosalia/': '/services/soda-blasting/rosalia-ks/',
  '/services/soda-blasting/rose-hill/': '/services/soda-blasting/rose-hill-ks/',
  '/services/soda-blasting/sedgwick/': '/services/soda-blasting/sedgwick-ks/',
  '/services/soda-blasting/valley-center/': '/services/soda-blasting/valley-center-ks/',
  '/services/soda-blasting/whitewater/': '/services/soda-blasting/whitewater-ks/',
  '/services/soda-blasting/wichita/': '/services/soda-blasting/wichita-ks/',

  // /services/ non-ks -> ks (vapor-barrier)
  '/services/vapor-barrier/andover/': '/services/vapor-barrier/andover-ks/',
  '/services/vapor-barrier/augusta/': '/services/vapor-barrier/augusta-ks/',
  '/services/vapor-barrier/bel-aire/': '/services/vapor-barrier/bel-aire-ks/',
  '/services/vapor-barrier/benton/': '/services/vapor-barrier/benton-ks/',
  '/services/vapor-barrier/burns/': '/services/vapor-barrier/burns-ks/',
  '/services/vapor-barrier/cassoday/': '/services/vapor-barrier/cassoday-ks/',
  '/services/vapor-barrier/clearwater/': '/services/vapor-barrier/clearwater-ks/',
  '/services/vapor-barrier/derby/': '/services/vapor-barrier/derby-ks/',
  '/services/vapor-barrier/douglass/': '/services/vapor-barrier/douglass-ks/',
  '/services/vapor-barrier/eastborough/': '/services/vapor-barrier/eastborough-ks/',
  '/services/vapor-barrier/el-dorado/': '/services/vapor-barrier/el-dorado-ks/',
  '/services/vapor-barrier/eureka/': '/services/vapor-barrier/eureka-ks/',
  '/services/vapor-barrier/goddard/': '/services/vapor-barrier/goddard-ks/',
  '/services/vapor-barrier/haysville/': '/services/vapor-barrier/haysville-ks/',
  '/services/vapor-barrier/leon/': '/services/vapor-barrier/leon-ks/',
  '/services/vapor-barrier/maize/': '/services/vapor-barrier/maize-ks/',
  '/services/vapor-barrier/newton/': '/services/vapor-barrier/newton-ks/',
  '/services/vapor-barrier/park-city/': '/services/vapor-barrier/park-city-ks/',
  '/services/vapor-barrier/potwin/': '/services/vapor-barrier/potwin-ks/',
  '/services/vapor-barrier/rosalia/': '/services/vapor-barrier/rosalia-ks/',
  '/services/vapor-barrier/rose-hill/': '/services/vapor-barrier/rose-hill-ks/',
  '/services/vapor-barrier/sedgwick/': '/services/vapor-barrier/sedgwick-ks/',
  '/services/vapor-barrier/valley-center/': '/services/vapor-barrier/valley-center-ks/',
  '/services/vapor-barrier/whitewater/': '/services/vapor-barrier/whitewater-ks/',
  '/services/vapor-barrier/wichita/': '/services/vapor-barrier/wichita-ks/',

  // /services/ non-ks -> ks (water-damage-restoration)
  '/services/water-damage-restoration/andover/': '/services/water-damage-restoration/andover-ks/',
  '/services/water-damage-restoration/augusta/': '/services/water-damage-restoration/augusta-ks/',
  '/services/water-damage-restoration/bel-aire/': '/services/water-damage-restoration/bel-aire-ks/',
  '/services/water-damage-restoration/benton/': '/services/water-damage-restoration/benton-ks/',
  '/services/water-damage-restoration/burns/': '/services/water-damage-restoration/burns-ks/',
  '/services/water-damage-restoration/cassoday/': '/services/water-damage-restoration/cassoday-ks/',
  '/services/water-damage-restoration/clearwater/': '/services/water-damage-restoration/clearwater-ks/',
  '/services/water-damage-restoration/derby/': '/services/water-damage-restoration/derby-ks/',
  '/services/water-damage-restoration/douglass/': '/services/water-damage-restoration/douglass-ks/',
  '/services/water-damage-restoration/eastborough/': '/services/water-damage-restoration/eastborough-ks/',
  '/services/water-damage-restoration/el-dorado/': '/services/water-damage-restoration/el-dorado-ks/',
  '/services/water-damage-restoration/eureka/': '/services/water-damage-restoration/eureka-ks/',
  '/services/water-damage-restoration/goddard/': '/services/water-damage-restoration/goddard-ks/',
  '/services/water-damage-restoration/haysville/': '/services/water-damage-restoration/haysville-ks/',
  '/services/water-damage-restoration/leon/': '/services/water-damage-restoration/leon-ks/',
  '/services/water-damage-restoration/maize/': '/services/water-damage-restoration/maize-ks/',
  '/services/water-damage-restoration/newton/': '/services/water-damage-restoration/newton-ks/',
  '/services/water-damage-restoration/park-city/': '/services/water-damage-restoration/park-city-ks/',
  '/services/water-damage-restoration/potwin/': '/services/water-damage-restoration/potwin-ks/',
  '/services/water-damage-restoration/rosalia/': '/services/water-damage-restoration/rosalia-ks/',
  '/services/water-damage-restoration/rose-hill/': '/services/water-damage-restoration/rose-hill-ks/',
  '/services/water-damage-restoration/sedgwick/': '/services/water-damage-restoration/sedgwick-ks/',
  '/services/water-damage-restoration/valley-center/': '/services/water-damage-restoration/valley-center-ks/',
  '/services/water-damage-restoration/whitewater/': '/services/water-damage-restoration/whitewater-ks/',
  '/services/water-damage-restoration/wichita/': '/services/water-damage-restoration/wichita-ks/',

  // Root blog posts -> /blog/
  '/affordable-carpet-cleaning-for-busy-homes/': '/blog/affordable-carpet-cleaning-for-busy-homes/',
  '/affordable-home-restoration-el-dorado-help/': '/blog/affordable-home-restoration-el-dorado-help/',
  '/air-duct-cleaning-a-key-step-for-healthy-living/': '/blog/air-duct-cleaning-a-key-step-for-healthy-living/',
  '/air-duct-cleaning-that-boosts-home-efficiency/': '/blog/air-duct-cleaning-that-boosts-home-efficiency/',
  '/best-carpet-cleaning-in-el-dorado-fast-reliable/': '/blog/best-carpet-cleaning-in-el-dorado-fast-reliable/',
  '/boost-hvac-efficiency-with-air-duct-cleaning/': '/blog/boost-hvac-efficiency-with-air-duct-cleaning/',
  '/carpet-cleaning-101-how-often-should-you-really-clean-your-carpets/': '/blog/carpet-cleaning-101-how-often-should-you-really-clean-your-carpets/',
  '/carpet-cleaning-before-after-andover-ks-good-to-be-clean/': '/blog/carpet-cleaning-before-after-andover-ks-good-to-be-clean/',
  '/carpet-cleaning-for-allergies-why-el-dorado-ks-families-should-act-now/': '/blog/carpet-cleaning-for-allergies-why-el-dorado-ks-families-should-act-now/',
  '/carpet-cleaning-frequency-guide-el-dorado-ks-good-to-be-clean/': '/blog/carpet-cleaning-frequency-guide-el-dorado-ks-good-to-be-clean/',
  '/carpet-cleaning-in-el-dorado-your-1-choice/': '/blog/carpet-cleaning-in-el-dorado-your-1-choice/',
  '/carpet-cleaning-tips-to-keep-your-floors-fresh-and-spotless/': '/blog/carpet-cleaning-tips-to-keep-your-floors-fresh-and-spotless/',
  '/diy-carpet-cleaning-vs-hiring-professionals-whats-best-for-el-dorado-ks-homes/': '/blog/diy-carpet-cleaning-vs-hiring-professionals-whats-best-for-el-dorado-ks-homes/',
  '/dryer-vent-cleaning-services-el-dorado-ks-good-to-be-clean/': '/blog/dryer-vent-cleaning-services-el-dorado-ks-good-to-be-clean/',
  '/emergency-carpet-cleaning-services/': '/blog/emergency-carpet-cleaning-services/',
  '/expert-carpet-stain-removal-guide-for-homeowners-in-el-dorado-ks/': '/blog/expert-carpet-stain-removal-guide-for-homeowners-in-el-dorado-ks/',
  '/expert-home-restoration-el-dorado-solutions/': '/blog/expert-home-restoration-el-dorado-solutions/',
  '/fast-reliable-carpet-cleaning-in-el-dorado/': '/blog/fast-reliable-carpet-cleaning-in-el-dorado/',
  '/fire-and-smoke-damage-how-to-restore-your-home-after-a-fire/': '/blog/fire-and-smoke-damage-how-to-restore-your-home-after-a-fire/',
  '/home-restoration-el-dorado-services-guide/': '/blog/home-restoration-el-dorado-services-guide/',
  '/home-restoration-guide-for-water-fire-and-mold-damage/': '/blog/home-restoration-guide-for-water-fire-and-mold-damage/',
  '/home-restoration-services-for-local-property-owners/': '/blog/home-restoration-services-for-local-property-owners/',
  '/home-restoration-services-signs-your-property-needs-help/': '/blog/home-restoration-services-signs-your-property-needs-help/',
  '/home-restoration-solutions-to-restore-comfort-and-safety/': '/blog/home-restoration-solutions-to-restore-comfort-and-safety/',
  '/home-restoration-tips-to-protect-and-increase-property-value/': '/blog/home-restoration-tips-to-protect-and-increase-property-value/',
  '/how-air-duct-cleaning-improves-your-homes/': '/blog/how-air-duct-cleaning-improves-your-homes/',
  '/how-carpet-cleaning-improves-air-quality-fast/': '/blog/how-carpet-cleaning-improves-air-quality-fast/',
  '/how-expert-restoration-services-handle-mold-removal/': '/blog/how-expert-restoration-services-handle-mold-removal/',
  '/how-restoration-services-save-homes-after-water-damage/': '/blog/how-restoration-services-save-homes-after-water-damage/',
  '/how-smoke-damage-repair-protects-indoor-air-quality/': '/blog/how-smoke-damage-repair-protects-indoor-air-quality/',
  '/how-smoke-damage-repair-restores-your-home/': '/blog/how-smoke-damage-repair-restores-your-home/',
  '/how-to-choose-the-best-air-duct-cleaning/': '/blog/how-to-choose-the-best-air-duct-cleaning/',
  '/local-home-restoration-solutions-for-property-damage/': '/blog/local-home-restoration-solutions-for-property-damage/',
  '/mold-myths-debunked-what-every-homeowner-needs-to-know/': '/blog/mold-myths-debunked-what-every-homeowner-needs-to-know/',
  '/pet-odor-stain-removal-carpet-cleaning-el-dorado-ks-good-to-be-clean/': '/blog/pet-odor-stain-removal-carpet-cleaning-el-dorado-ks-good-to-be-clean/',
  '/professional-air-duct-cleaning-services-for-cleaner-air/': '/blog/professional-air-duct-cleaning-services-for-cleaner-air/',
  '/professional-carpet-cleaning-services-for-a-healthier-home/': '/blog/professional-carpet-cleaning-services-for-a-healthier-home/',
  '/professional-home-restoration-for-residential-properties/': '/blog/professional-home-restoration-for-residential-properties/',
  '/refresh-your-floors-with-el-dorado-carpet-cleaning/': '/blog/refresh-your-floors-with-el-dorado-carpet-cleaning/',
  '/restore-your-home-faster-with-smoke-damage-repair-experts/': '/blog/restore-your-home-faster-with-smoke-damage-repair-experts/',
  '/safe-and-professional-mold-removal-services/': '/blog/safe-and-professional-mold-removal-services/',
  '/seasonal-carpet-care-summer-cleaning-in-el-dorado-ks-good-to-be-clean/': '/blog/seasonal-carpet-care-summer-cleaning-in-el-dorado-ks-good-to-be-clean/',
  '/the-benefits-of-a-house-cleaning-subscription-why-its-worth-it/': '/blog/the-benefits-of-a-house-cleaning-subscription-why-its-worth-it/',
  '/the-hidden-dangers-of-dirty-air-ducts-and-why-you-should-clean-them/': '/blog/the-hidden-dangers-of-dirty-air-ducts-and-why-you-should-clean-them/',
  '/top-5-signs-your-air-ducts-need-cleaning-el-dorado-ks-good-to-be-clean/': '/blog/top-5-signs-your-air-ducts-need-cleaning-el-dorado-ks-good-to-be-clean/',
  '/top-benefits-of-hiring-professional-restoration-services/': '/blog/top-benefits-of-hiring-professional-restoration-services/',
  '/trusted-carpet-cleaning-el-dorado-experts-near-you/': '/blog/trusted-carpet-cleaning-el-dorado-experts-near-you/',
  '/trusted-home-restoration-el-dorado-experts/': '/blog/trusted-home-restoration-el-dorado-experts/',
  '/trusted-home-restoration-for-homes-and-businesses-nearby/': '/blog/trusted-home-restoration-for-homes-and-businesses-nearby/',
  '/upholstery-cleaning-guide-el-dorado-ks-good-to-be-clean/': '/blog/upholstery-cleaning-guide-el-dorado-ks-good-to-be-clean/',
  '/water-damage-restoration-what-to-do-in-the-first-24-hours/': '/blog/water-damage-restoration-what-to-do-in-the-first-24-hours/',
  '/what-to-expect-during-a-smoke-damage-repair-process/': '/blog/what-to-expect-during-a-smoke-damage-repair-process/',
  '/what-to-expect-from-water-damage-restoration/': '/blog/what-to-expect-from-water-damage-restoration/',
  '/why-air-duct-cleaning-matters-for-allergy-and-dust-control/': '/blog/why-air-duct-cleaning-matters-for-allergy-and-dust-control/',
  '/why-professional-restoration-services-matter-after-fires/': '/blog/why-professional-restoration-services-matter-after-fires/',
  '/why-smoke-damage-repair-is-vital-after-a-house-fire/': '/blog/why-smoke-damage-repair-is-vital-after-a-house-fire/',
};

export async function onRequest(context) {
  const url = new URL(context.request.url);
  const pathname = url.pathname.endsWith('/') ? url.pathname : url.pathname + '/';
  const destination = REDIRECTS[pathname];
  if (destination) {
    return Response.redirect(new URL(destination, url.origin).toString(), 301);
  }
  return context.next();
}
